language: android
android:
  components:

    - build-tools-19.1.0
    - android-22
    - sys-img-armeabi-v7a-android-22
    - sys-img-x86-android-17
 - build-tools-18.1.1
    - android-18
    - extra
branches:
  only:
    - test
